
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "src: /var/snap/jenkins/5047/workspace/prog5/target/MavenAnsibleWebApp1.war"
        dest: "/opt/tomcat/webapps/MyMavenAnsibleWebApp.war"
        remote_src: no

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/startup.sh
